build: 
	lessc red/styles.less > red/styles.css
	lessc orange/styles.less > orange/styles.css
	lessc gold/styles.less > gold/styles.css
	lessc yellow/styles.less > yellow/styles.css
	lessc green/styles.less > green/styles.css
	lessc teal/styles.less > teal/styles.css
	lessc aqua/styles.less > aqua/styles.css
	lessc cyan/styles.less > cyan/styles.css
	lessc blue/styles.less > blue/styles.css
	lessc violet/styles.less > violet/styles.css
	lessc magenta/styles.less > magenta/styles.css
	lessc brown/styles.less > brown/styles.css
	lessc grey/styles.less > grey/styles.css