build: 
	lessc binary/medium/styles.less > binary/medium/styles.css 
	lessc binary/light/styles.less > binary/light/styles.css 
	lessc binary/dark/styles.less > binary/dark/styles.css
 
	lessc non-binary/medium/styles.less > non-binary/medium/styles.css 
	lessc non-binary/light/styles.less > non-binary/light/styles.css 
	lessc non-binary/dark/styles.less > non-binary/dark/styles.css

	lessc monochrome/medium/styles.less > monochrome/medium/styles.css 
	lessc monochrome/light/styles.less > monochrome/light/styles.css 
	lessc monochrome/dark/styles.less > monochrome/dark/styles.css

	lessc shaded/medium/styles.less > shaded/medium/styles.css 
	lessc shaded/light/styles.less > shaded/light/styles.css 
	lessc shaded/dark/styles.less > shaded/dark/styles.css 

	lessc colored/red/styles.less > colored/red/styles.css
	lessc colored/orange/styles.less > colored/orange/styles.css
	lessc colored/gold/styles.less > colored/gold/styles.css
	lessc colored/yellow/styles.less > colored/yellow/styles.css
	lessc colored/green/styles.less > colored/green/styles.css
	lessc colored/teal/styles.less > colored/teal/styles.css
	lessc colored/aqua/styles.less > colored/aqua/styles.css
	lessc colored/cyan/styles.less > colored/cyan/styles.css
	lessc colored/blue/styles.less > colored/blue/styles.css
	lessc colored/violet/styles.less > colored/violet/styles.css
	lessc colored/magenta/styles.less > colored/magenta/styles.css
	lessc colored/brown/styles.less > colored/brown/styles.css
	lessc colored/grey/styles.less > colored/grey/styles.css

	lessc colorful/red/styles.less > colorful/red/styles.css
	lessc colorful/orange/styles.less > colorful/orange/styles.css
	lessc colorful/gold/styles.less > colorful/gold/styles.css
	lessc colorful/yellow/styles.less > colorful/yellow/styles.css
	lessc colorful/green/styles.less > colorful/green/styles.css
	lessc colorful/teal/styles.less > colorful/teal/styles.css
	lessc colorful/aqua/styles.less > colorful/aqua/styles.css
	lessc colorful/cyan/styles.less > colorful/cyan/styles.css
	lessc colorful/blue/styles.less > colorful/blue/styles.css
	lessc colorful/violet/styles.less > colorful/violet/styles.css
	lessc colorful/magenta/styles.less > colorful/magenta/styles.css
	lessc colorful/brown/styles.less > colorful/brown/styles.css
	lessc colorful/grey/styles.less > colorful/grey/styles.css

	lessc accented/red/styles.less > accented/red/styles.css
	lessc accented/orange/styles.less > accented/orange/styles.css
	lessc accented/gold/styles.less > accented/gold/styles.css
	lessc accented/yellow/styles.less > accented/yellow/styles.css
	lessc accented/green/styles.less > accented/green/styles.css
	lessc accented/teal/styles.less > accented/teal/styles.css
	lessc accented/aqua/styles.less > accented/aqua/styles.css
	lessc accented/cyan/styles.less > accented/cyan/styles.css
	lessc accented/blue/styles.less > accented/blue/styles.css
	lessc accented/violet/styles.less > accented/violet/styles.css
	lessc accented/magenta/styles.less > accented/magenta/styles.css
	lessc accented/brown/styles.less > accented/brown/styles.css
	lessc accented/grey/styles.less > accented/grey/styles.css